# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.account_label = QtWidgets.QLabel(Form)
        self.account_label.setObjectName("account_label")
        self.gridLayout.addWidget(self.account_label, 0, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 1, 0, 1, 1)
        self.account_lineEdit = QtWidgets.QLineEdit(Form)
        self.account_lineEdit.setObjectName("account_lineEdit")
        self.gridLayout.addWidget(self.account_lineEdit, 0, 1, 1, 1)
        self.password_lineEdit = QtWidgets.QLineEdit(Form)
        self.password_lineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setDragEnabled(False)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 1, 1, 1, 1)
        self.check_button = QtWidgets.QPushButton(Form)
        self.check_button.setEnabled(True)
        self.check_button.setObjectName("check_button")
        self.gridLayout.addWidget(self.check_button, 2, 1, 1, 1)
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setEnabled(True)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.account_reminder = QtWidgets.QLabel(Form)
        self.account_reminder.setAutoFillBackground(True)
        self.account_reminder.setStyleSheet("color: rgb(255, 0, 0);")
        self.account_reminder.setText("")
        self.account_reminder.setObjectName("account_reminder")
        self.gridLayout_2.addWidget(self.account_reminder, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.auto_on = QtWidgets.QPushButton(Form)
        self.auto_on.setCheckable(False)
        self.auto_on.setObjectName("auto_on")
        self.gridLayout_2.addWidget(self.auto_on, 3, 0, 1, 2)
        self.auto_off = QtWidgets.QPushButton(Form)
        self.auto_off.setObjectName("auto_off")
        self.gridLayout_2.addWidget(self.auto_off, 4, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        self.policy_button = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.policy_button.setFont(font)
        self.policy_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.policy_button.setAutoFillBackground(False)
        self.policy_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 85, 255);")
        self.policy_button.setObjectName("policy_button")
        self.gridLayout_2.addWidget(self.policy_button, 5, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AutoFill"))
        self.account_label.setText(_translate("Form", "<html><head/><body><p>账号：</p></body></html>"))
        self.password_label.setText(_translate("Form", "<html><head/><body><p>密码：</p></body></html>"))
        self.check_button.setText(_translate("Form", "验证"))
        self.save_button.setText(_translate("Form", "保存"))
        self.auto_on.setText(_translate("Form", "启用定时打卡"))
        self.auto_off.setText(_translate("Form", "停用定时打卡"))
        self.policy_button.setText(_translate("Form", "提示与隐私政策"))
