# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'policy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.accept_box = QtWidgets.QCheckBox(Form)
        self.accept_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accept_box.setChecked(False)
        self.accept_box.setTristate(False)
        self.accept_box.setObjectName("accept_box")
        self.gridLayout.addWidget(self.accept_box, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 3)
        self.back_button = QtWidgets.QPushButton(Form)
        self.back_button.setObjectName("back_button")
        self.gridLayout.addWidget(self.back_button, 1, 2, 1, 1)

        self.retranslateUi(Form)
        self.back_button.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "提示与隐私政策"))
        self.accept_box.setText(_translate("Form", "我同意以上服务条款"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">AutoFill</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">版本号</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">version 1.0</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">提示</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1. 为了避免软件受恶意更改的风险，建议在</span><a href=\"https://caveallegory.cn/share/\"><span style=\" font-size:12pt; text-decoration: underline; color:#0000ff;\">开发者的个人网站</span></a><span style=\" font-size:12pt;\">上下载本软件,在本地校验本软件的 MD5码，并与网站上的MD5码相比对。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2. 建议在使用前将本软件放在一个</span><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">固定的文件夹</span><span style=\" font-size:12pt;\">中，卸载时</span><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">先“停用自动打卡”</span><span style=\" font-size:12pt;\">，之后删除整个文件夹即可。分享软件时请</span><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">仅分享exe文件</span><span style=\" font-size:12pt;\">，勿传其他文件。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3. 本软件需先填写账号信息并保存，可点击“验证”核对账号正确性。最后点击“启用自动打卡”，则您的电脑会在合适时间且间隔30分钟尝试打卡，直至打卡成功。</span><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">电脑锁屏、睡眠可能会导致打卡失败</span><span style=\" font-size:12pt;\">。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">4. 本软件目前仅限于实现</span><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">在校</span><span style=\" font-size:12pt; color:#000000;\">自动</span><span style=\" font-size:12pt;\">打卡，当您在校外时记得及时停用自动打卡服务。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">服务条款</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1. 您必须同意以下所列条款，方可使用本软件服务。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2. 您应当在不修改本软件代码的条件下使用本软件。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3. 您应当知晓并承担使用本软件的一切风险，如提交错误健康信息、软件打卡失败等风险。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">4. 本软件不可替代校方提供的打卡渠道，应始终作为您的辅助工具使用。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">5. 您应当在使用本软件时遵守相关法律法规及学校规定。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">6. 本软件仅在本地加密存储您的账号及密码，并仅用于自动打卡时登录学校账户完成打卡。本软件不会将您的敏感信息提供给第三方。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">7. 如出现您的健康状况、打卡信息发生变化，或本软件与法律法规及学校规定冲突，或您不再接受本服务条款等情况，请立即停止使用本软件！</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">8. 本软件的使用选择权完全归使用者所有，一切使用后果归使用方负责，开发者不承担您违规使用所造成的任何责任！</span></p></body></html>"))
        self.back_button.setText(_translate("Form", "返回"))
